### ISSUE TITLE
Scottish data

### ISSUE THREAD

**Issue by RobJN** [Cj-Malone/IIP-Downloader#3]
The Scottish data lives elsewhere. https://ros.locationcentre.co.uk/inspire/

Steps:
- [x] Determine format
- [x] Work out how to handle this with ogr2ogr
- [x] Update script

**Comment by RobJN** [comment]
The format is an ESRI shapefile. In fact the zip file (which ogr2ogr can read) includes two separate layers. One using British National Grid projection, the other using a European projection (ETRS89 / ESPG:4258). Example structure for Aberdeen:

- ABN.zip
- Containing ABN_bng.shp and ABN_etrs89.shp

**Comment by Cj-Malone** [comment]
OK, I've got Scotland downloading and unzipping. When you know which file you want to convert and import into `combined.sqlite` we can do that too.

I've added Scotland to the end of the `local authorities.csv` so if you just want to test it remove the English links above.

**Comment by RobJN** [comment]
In QGIS you don't need to unzip ESRI Shapefile folders. The manual for ogr2ogr suggests using the virtual file system option (appending /vsizip/) and it turns out we can do this for not just the Scotland data but also the England & Wales data. In #4 the script is amended to not unzip and is therefore quicker.
